### ISSUE TITLE
Don't work when Checkbox has a name.

### ISSUE THREAD

**Issue by ghost** [MoonfireSeco/strawpoll-bot#1]
Hello! Nice work but when the checkbox has name --> Couldn't find option "number"
Only works if in checkbox there is a number.
Can you fix that?
Thanks and have a nice day!

**Comment by Hunam6** [comment]
Don't work for me too :/

**Comment by Milkdrop** [comment]
Hello! This issue has been fixed. Since I made the script the site has been updated and changed the way options were rendered in the page. That's why it stopped working.

Should be good now.
