### ISSUE TITLE
missing arguments

### ISSUE THREAD

**Issue by TheALoafOfBread** [MoonfireSeco/strawpoll-bot#10]
usage: main.py [-h] [-f F] [-m M] [-p] id option
main.py: error: the following arguments are required: id, option
is the error message

**Comment by Hyper100** [comment]
Have you tried giving it the id and option?

**Comment by devender15** [comment]
> Have you tried giving it the id and option?

It requires an integer Id but we can only get a string Id like X3nk62X6YyE

**Comment by Milkdrop** [comment]
This is because string IDs are from strawpoll.com, this script only worked for strawpoll.me which has been shut down
