### ISSUE TITLE
Error launching the strawpoll bot with proxy

### ISSUE THREAD

**Issue by null15** [MoonfireSeco/strawpoll-bot#11]
-> python3 script.py 4y9322fp5 2 -p

Traceback (most recent call last):
  File "C:\Users\Raiko\Desktop\strawpoll bot\script.py", line 153, in <module>
    prepare (args, motd)
  File "C:\Users\Raiko\Desktop\strawpoll bot\script.py", line 84, in prepare
    checkboxID = str (int (checkboxID) + opt - 1)
ValueError: invalid literal for int() with base 10: ''

**Comment by BoozyAF** [comment]
Having the same error, right now trying to fix it. Will post the fix here or make a push request.

**Comment by hackyGH** [comment]
Is it fixed? I am still getting the same error
![Screenshot from 2022-12-12 09-31-28](https://user-images.githubusercontent.com/52008031/206957886-edbb0503-ce8b-4542-8c6d-7c28440b22e3.png)

**Comment by Milkdrop** [comment]
You are trying to use it for strawpoll.com which will not work. This script was only written for strawpoll.me which has been shut down :(
