### ISSUE TITLE
Invalid Proxy

### ISSUE THREAD

**Issue by ablaszkiewicz** [MoonfireSeco/strawpoll-bot#2]
Hello, I am getting this error: Vote Unsuccessful (Invalid Proxy) after using following command
`python script.py 19452453 2 -p`
Poll has ip protection so I have to use proxies. Tried to manually create proxies.txt and program successfuly read proxies from the file but I am still getting the same error.

**Comment by Milkdrop** [comment]
That error usually means that the proxies you have inputted don't work properly / aren't stable enough.
