### ISSUE TITLE
Traceback ValueError

### ISSUE THREAD

**Issue by paufase** [MoonfireSeco/strawpoll-bot#3]
It gives an error:
`Traceback (most recent call last):
  File "script.py", line 146, in <module>
    prepare (args, motd)
  File "script.py", line 83, in prepare
    checkboxID = str (int (checkboxID) + opt - 1)
ValueError: invalid literal for int() with base 10: ''`

**Comment by Milkdrop** [comment]
Can you provide the poll URL that causes this?

**Comment by m7mdcc** [comment]
Same error ,, 

POLL URL  :https://strawpoll.com/2f93s8ar

Uh oh , so this for strawpoll.me not strawpoll.com LOL
