### ISSUE TITLE
Vote Unsuccessful (Invalid Proxy)

### ISSUE THREAD

**Issue by PxT00** [MoonfireSeco/strawpoll-bot#5]
When I use the argument "-p" the proxy doesnt work and i cant vote
![image](https://user-images.githubusercontent.com/65025260/81995060-b00cc180-961f-11ea-97f8-6e80c07b2b87.png)

**Comment by Milkdrop** [comment]
You could change the proxy list

**Comment by PxT00** [comment]
> You could change the proxy list

Yeah, i already did this LOL. Thanks for the help.
