### ISSUE TITLE
Vote unsuccessful

### ISSUE THREAD

**Issue by Steccah** [MoonfireSeco/strawpoll-bot#8]
If the poll has the multiple poll answers activated there is the following error, even if there is no duplication checking
>Vote Unsuccessful (The poll may be doing an IP Check. Use option -p)

Also it crashes if you use a proxy list

**Comment by KeparYTbcc** [comment]
same

**Comment by KeparYTbcc** [comment]
r = adapter.send(request, **kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 414, in send

**Comment by Steccah** [comment]
He moved to GitLab and i think the project is fully abandoned

**Comment by Milkdrop** [comment]
The issue when voting on multiple-choice polls should now be fixed.
